DROP DATABASE IF EXISTS zapatos_cris;
CREATE DATABASE zapatos_cris;
USE zapatos_cris;

CREATE TABLE GENEROS(
	ID_GENERO INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE_GENERO VARCHAR(15)
)Engine=InnoDB;

CREATE TABLE TIPO_USUARIOS(
	ID_TIPO_USUARIO INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE_TIPO_USUARIO VARCHAR(25)
)Engine=InnoDB;

CREATE TABLE PRODUCTOS(
	ID_PRODUCTO INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE_PRODUCTO VARCHAR(25) NOT NULL,
    IMAGEN LONGBLOB NOT NULL,
    PRECIO INT NOT NULL,
    CANTIDAD INT NOT NULL
)Engine=InnoDB;
CREATE TABLE USUARIOS(
	ID_USUARIO INT PRIMARY KEY AUTO_INCREMENT,
	IDENTIFICACION VARCHAR(20) NOT NULL,
    PRIMER_NOMBRE VARCHAR(15) NOT NULL,
    SEGUNDO_NOMBRE VARCHAR(15),
    PRIMER_APELLIDO VARCHAR(15) NOT NULL,
    SEGUNDO_APELLIDO VARCHAR(15) NOT NULL,
    CORREO VARCHAR(45),
    CLAVE VARCHAR(20) NOT NULL,
    DIRECCION VARCHAR(30) NOT NULL,
    TELEFONO INT NOT NULL,
	ID_TIPO_USUARIO_FK INT NOT NULL,
    ID_GENERO_FK INT NOT NULL,
	FOREIGN KEY (ID_TIPO_USUARIO_FK) REFERENCES TIPO_USUARIOS(ID_TIPO_USUARIO),
    FOREIGN KEY (ID_GENERO_FK) REFERENCES GENEROS(ID_GENERO)
)Engine=InnoDB;

CREATE TABLE ENCABEZADO_VENTAS(
	NRO_FACTURA INT PRIMARY key AUTO_INCREMENT,
    FECHA_COMPRA DATE NOT NULL,
	ID_USUARIO_FK INT NOT NULL,
    FOREIGN KEY (ID_USUARIO_FK) REFERENCES USUARIOS(ID_USUARIO)
)Engine=InnoDB;


CREATE TABLE DETALLE_COMPRAS(
	ID_COMPRA INT PRIMARY KEY AUTO_INCREMENT,
	CANTIDAD INT NOT NULL,
    TOTAL INT,
    TALLAS VARCHAR(5),
    ID_PRODUCTO_FK INT NOT NULL,
    NRO_FACTURA_FK INT NOT NULL,
	FOREIGN KEY (NRO_FACTURA_FK) REFERENCES ENCABEZADO_VENTAS(NRO_FACTURA),
    FOREIGN KEY (ID_PRODUCTO_FK) REFERENCES PRODUCTOS(ID_PRODUCTO)
)Engine=InnoDB;
/*DESCRIBIR INFORMACION DE LA TABLA:
desc USUARIOS*/